# Generated by Django 2.0.7 on 2018-07-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180713_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='author',
            field=models.ManyToManyField(null=True, to='app1.Author'),
        ),
    ]
